// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _mat_mul_wrap_HH_
#define _mat_mul_wrap_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "copy_mat.h"
#include "mat_mul_wrap_matCbkb.h"
#include "mat_mul_wrap_matBcud.h"

namespace ap_rtl {

struct mat_mul_wrap : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<14> > matA_address0;
    sc_out< sc_logic > matA_ce0;
    sc_in< sc_lv<32> > matA_q0;
    sc_out< sc_lv<14> > matB_address0;
    sc_out< sc_logic > matB_ce0;
    sc_in< sc_lv<32> > matB_q0;
    sc_out< sc_lv<14> > matC_address0;
    sc_out< sc_logic > matC_ce0;
    sc_out< sc_logic > matC_we0;
    sc_out< sc_lv<32> > matC_d0;


    // Module declarations
    mat_mul_wrap(sc_module_name name);
    SC_HAS_PROCESS(mat_mul_wrap);

    ~mat_mul_wrap();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    mat_mul_wrap_matCbkb* matC_local_U;
    mat_mul_wrap_matBcud* matB_local_U;
    mat_mul_wrap_matBcud* matA_local_U;
    copy_mat* grp_copy_mat_fu_28;
    copy_mat* grp_copy_mat_fu_36;
    copy_mat* grp_copy_mat_fu_44;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > matC_local_q0;
    sc_signal< sc_logic > grp_copy_mat_fu_28_ap_start;
    sc_signal< sc_logic > grp_copy_mat_fu_28_ap_done;
    sc_signal< sc_logic > grp_copy_mat_fu_28_ap_idle;
    sc_signal< sc_logic > grp_copy_mat_fu_28_ap_ready;
    sc_signal< sc_lv<14> > grp_copy_mat_fu_28_src_address0;
    sc_signal< sc_logic > grp_copy_mat_fu_28_src_ce0;
    sc_signal< sc_lv<14> > grp_copy_mat_fu_28_dest_address0;
    sc_signal< sc_logic > grp_copy_mat_fu_28_dest_ce0;
    sc_signal< sc_logic > grp_copy_mat_fu_28_dest_we0;
    sc_signal< sc_lv<32> > grp_copy_mat_fu_28_dest_d0;
    sc_signal< sc_logic > grp_copy_mat_fu_36_ap_start;
    sc_signal< sc_logic > grp_copy_mat_fu_36_ap_done;
    sc_signal< sc_logic > grp_copy_mat_fu_36_ap_idle;
    sc_signal< sc_logic > grp_copy_mat_fu_36_ap_ready;
    sc_signal< sc_lv<14> > grp_copy_mat_fu_36_src_address0;
    sc_signal< sc_logic > grp_copy_mat_fu_36_src_ce0;
    sc_signal< sc_lv<14> > grp_copy_mat_fu_36_dest_address0;
    sc_signal< sc_logic > grp_copy_mat_fu_36_dest_ce0;
    sc_signal< sc_logic > grp_copy_mat_fu_36_dest_we0;
    sc_signal< sc_lv<32> > grp_copy_mat_fu_36_dest_d0;
    sc_signal< sc_logic > grp_copy_mat_fu_44_ap_start;
    sc_signal< sc_logic > grp_copy_mat_fu_44_ap_done;
    sc_signal< sc_logic > grp_copy_mat_fu_44_ap_idle;
    sc_signal< sc_logic > grp_copy_mat_fu_44_ap_ready;
    sc_signal< sc_lv<14> > grp_copy_mat_fu_44_src_address0;
    sc_signal< sc_logic > grp_copy_mat_fu_44_src_ce0;
    sc_signal< sc_lv<14> > grp_copy_mat_fu_44_dest_address0;
    sc_signal< sc_logic > grp_copy_mat_fu_44_dest_ce0;
    sc_signal< sc_logic > grp_copy_mat_fu_44_dest_we0;
    sc_signal< sc_lv<32> > grp_copy_mat_fu_44_dest_d0;
    sc_signal< sc_logic > ap_reg_grp_copy_mat_fu_28_ap_start;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_reg_grp_copy_mat_fu_36_ap_start;
    sc_signal< sc_logic > ap_reg_grp_copy_mat_fu_44_ap_start;
    sc_signal< bool > ap_block_state2_on_subcall_done;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_block_state2_on_subcall_done();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_grp_copy_mat_fu_28_ap_start();
    void thread_grp_copy_mat_fu_36_ap_start();
    void thread_grp_copy_mat_fu_44_ap_start();
    void thread_matA_address0();
    void thread_matA_ce0();
    void thread_matB_address0();
    void thread_matB_ce0();
    void thread_matC_address0();
    void thread_matC_ce0();
    void thread_matC_d0();
    void thread_matC_we0();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
